### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jnonino**
Hi, I added some changes. Let me know what you think!

## Google Analytics

Added piece of code to support Google Analytics. File `layouts/partials/head/scripts.html`.

## Google Search Console

There was an error when indexing a site with Google Search Console. The changes in the file `layouts/partials/head/meta.html` solve that problem.

Before the changes:
 image

After the changes:
image

### CODE REVIEW

**Comment by rawwerks** [comment]
the google search console fix would be particularly useful!

**Comment by lukeorth** [comment]
Hi @jnonino -- thank you for the contribution! 

Do you know if adding the Google Analytics feature will cause it to be enabled for everyone?  The [Hugo docs](https://gohugo.io/templates/internal/#google-analytics) state that you must add a tracking ID to the configuration file in order to make it work.  However, if a user doesn't provide a tracking number (because they don't want to use Google Analytics) will it still include Google scripts/tracking on their site?

**Comment by jnonino** [comment]
For what I've seen by not setting the ID in the configuration in dev site, the code I added does not do anything. It only works when you provide a Google Analytics ID

**Comment by lukeorth** [comment]
Perfect -- that's what I figured, but just wanted to double check.  Thanks again for the contribution!

**Pull request merged**
